# Generated by Django 5.0.1 on 2026-01-21 21:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('announcements', '0002_initial'),
        ('authentication', '0001_initial'),
        ('music', '0001_initial'),
        ('zones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaybackState',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('queue', models.JSONField(blank=True, default=list, verbose_name=models.UUIDField())),
                ('queue_position', models.IntegerField(default=0)),
                ('is_playing', models.BooleanField(db_index=True, default=False)),
                ('position', models.IntegerField(default=0)),
                ('volume', models.IntegerField(default=70)),
                ('current_playlists', models.JSONField(blank=True, default=list, verbose_name=models.UUIDField())),
                ('mode', models.CharField(choices=[('music', 'Music Only'), ('music+announcements', 'Music + Announcements'), ('announcements', 'Announcements Only')], default='music+announcements', max_length=20)),
                ('shuffle', models.BooleanField(default=False)),
                ('repeat', models.BooleanField(default=False)),
                ('announcement_interval_minutes', models.IntegerField(default=30)),
                ('fade_duration_seconds', models.IntegerField(default=3)),
                ('background_volume_percent', models.IntegerField(default=30)),
                ('last_updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('current_announcement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playback_states', to='announcements.announcement')),
                ('current_track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playback_states', to='music.musicfile')),
                ('zone', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='playback_state', to='zones.zone')),
            ],
            options={
                'db_table': 'playback_states',
                'indexes': [models.Index(fields=['zone', 'is_playing'], name='playback_st_zone_id_8b7175_idx'), models.Index(fields=['last_updated'], name='playback_st_last_up_f41b77_idx')],
            },
        ),
        migrations.CreateModel(
            name='PlayEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('instant', 'Instant'), ('scheduled', 'Scheduled')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('playing', 'Playing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='play_events', to='announcements.announcement')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='play_events', to='authentication.client')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_play_events', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='play_events', to='zones.device')),
            ],
            options={
                'db_table': 'play_events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['client', 'status'], name='play_events_client__ea0f67_idx'), models.Index(fields=['device', 'status'], name='play_events_device__ce45ff_idx'), models.Index(fields=['announcement', 'status'], name='play_events_announc_1da848_idx'), models.Index(fields=['event_type', 'status'], name='play_events_event_t_91ed26_idx')],
            },
        ),
    ]
