# Generated by Django 5.0.1 on 2026-01-21 21:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('file', models.FileField(upload_to='announcements/')),
                ('duration', models.IntegerField()),
                ('file_size', models.BigIntegerField()),
                ('is_tts', models.BooleanField(db_index=True, default=False)),
                ('tts_text', models.TextField(blank=True)),
                ('tts_voice', models.CharField(blank=True, max_length=50)),
                ('tts_provider', models.CharField(blank=True, max_length=50)),
                ('is_recording', models.BooleanField(default=False)),
                ('enabled', models.BooleanField(db_index=True, default=True)),
                ('category', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'announcements',
                'ordering': ['-created_at'],
            },
        ),
    ]
