# Generated by Django 5.0.1 on 2026-01-21 21:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('announcements', '0001_initial'),
        ('authentication', '0001_initial'),
        ('music', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='authentication.client'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_announcements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='announcement',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to='music.folder'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['client', 'enabled'], name='announcemen_client__594b16_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['client', 'is_tts'], name='announcemen_client__cb4620_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['folder', 'enabled'], name='announcemen_folder__c43d96_idx'),
        ),
    ]
