# Generated by Django 4.2.27 on 2026-01-25 20:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementTemplateFolder',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('category', models.CharField(choices=[('retail', 'Retail'), ('restaurant', 'Restaurant'), ('office', 'Office'), ('healthcare', 'Healthcare'), ('gym', 'Gym'), ('general', 'General')], db_index=True, max_length=50)),
                ('active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'db_table': 'announcement_template_folders',
                'ordering': ['category', 'name'],
                'indexes': [models.Index(fields=['category', 'active'], name='announcemen_categor_db1d85_idx')],
            },
        ),
        migrations.CreateModel(
            name='AnnouncementTemplate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('script', models.TextField()),
                ('category', models.CharField(choices=[('retail', 'Retail'), ('restaurant', 'Restaurant'), ('office', 'Office'), ('healthcare', 'Healthcare'), ('gym', 'Gym'), ('general', 'General')], db_index=True, max_length=50)),
                ('duration', models.IntegerField(default=0)),
                ('voice_type', models.CharField(choices=[('professional', 'Professional'), ('friendly', 'Friendly'), ('urgent', 'Urgent'), ('casual', 'Casual'), ('energetic', 'Energetic'), ('calm', 'Calm')], default='friendly', max_length=50)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='announcements.announcementtemplatefolder')),
            ],
            options={
                'db_table': 'announcement_templates',
                'ordering': ['folder', 'title'],
                'indexes': [models.Index(fields=['category', 'active'], name='announcemen_categor_7836b5_idx'), models.Index(fields=['folder', 'active'], name='announcemen_folder__acc066_idx')],
            },
        ),
    ]
