from __future__ import annotations
# -*- coding: utf-8 -*-
# code generated by Prisma. DO NOT EDIT.
# fmt: off
# -- template metadata.py.jinja --


PRISMA_MODELS: set[str] = {
    'User',
    'Track',
    'Schedule',
    'Announcement',
    'PlayLog',
}

RELATIONAL_FIELD_MAPPINGS: dict[str, dict[str, str]] = {
    'User': {
        'tracks': 'Track',
        'schedules': 'Schedule',
        'announcements': 'Announcement',
        'play_logs': 'PlayLog',
    },
    'Track': {
        'user': 'User',
    },
    'Schedule': {
        'user': 'User',
    },
    'Announcement': {
        'user': 'User',
        'play_logs': 'PlayLog',
    },
    'PlayLog': {
        'user': 'User',
        'announcement': 'Announcement',
    },
}

# fmt: on