# Generated by Django 5.0.1 on 2026-01-21 21:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('music', 'Music'), ('announcements', 'Announcements')], db_index=True, default='music', max_length=20)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='folder_covers/')),
                ('is_system', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='authentication.client')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_folders', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='music.folder')),
            ],
            options={
                'db_table': 'folders',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MusicFile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='music/')),
                ('filename', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField()),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('artist', models.CharField(blank=True, db_index=True, max_length=255)),
                ('album', models.CharField(blank=True, max_length=255)),
                ('genre', models.CharField(blank=True, max_length=100)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('duration', models.IntegerField()),
                ('cover_art', models.ImageField(blank=True, null=True, upload_to='covers/')),
                ('order', models.IntegerField(db_index=True, default=0)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='music_files', to='authentication.client')),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='music_files', to='music.folder')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_music', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'music_files',
                'ordering': ['folder', 'order', 'title'],
            },
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['client', 'type'], name='folders_client__51b663_idx'),
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['parent'], name='folders_parent__95398b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='folder',
            unique_together={('client', 'name', 'type')},
        ),
        migrations.AddIndex(
            model_name='musicfile',
            index=models.Index(fields=['client', 'folder'], name='music_files_client__3708cb_idx'),
        ),
        migrations.AddIndex(
            model_name='musicfile',
            index=models.Index(fields=['title', 'artist'], name='music_files_title_aa7655_idx'),
        ),
        migrations.AddIndex(
            model_name='musicfile',
            index=models.Index(fields=['folder', 'order'], name='music_files_folder__445bd5_idx'),
        ),
    ]
