# Generated by Django 4.2.27 on 2026-01-28 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_settings'),
        ('zones', '0002_zone_image'),
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='folder',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='folder',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='zones.zone'),
        ),
        migrations.AlterUniqueTogether(
            name='folder',
            unique_together={('client', 'zone', 'name', 'type')},
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['zone', 'type'], name='folders_zone_id_e0be4d_idx'),
        ),
    ]
