# Generated by Django 4.2.27 on 2026-01-28 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zones', '0002_zone_image'),
        ('music', '0002_add_zone_to_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicfile',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='music_files', to='zones.zone'),
        ),
    ]
