const fs = require('fs');
const p = 'lib/api.dart';
let c = fs.readFileSync(p, 'utf8');

// Add delete/rename functions after updateAnnouncement
const insertAfter = "Future<void> updateAnnouncement(String id, {String? title, String? folderId, String? zoneId, bool? enabled}) async {\r\n  final url = Uri.parse('$apiBase/announcements/$id/');\r\n  final body = <String, dynamic>{};\r\n  if (title != null) body['title'] = title;\r\n  if (folderId != null) body['folder_id'] = folderId;\r\n  if (zoneId != null) body['zone_id'] = zoneId;\r\n  if (enabled != null) body['enabled'] = enabled;\r\n  final res = await http.patch(url, headers: await _authHeaders(), body: jsonEncode(body));\r\n  if (res.statusCode < 200 || res.statusCode >= 300) {\r\n    throw Exception('Failed to update announcement: ${res.body}');\r\n  }\r\n}\r\n\r\n// --- Zones & Devices ---";

const replacement = "Future<void> updateAnnouncement(String id, {String? title, String? folderId, String? zoneId, bool? enabled}) async {\r\n  final url = Uri.parse('$apiBase/announcements/$id/');\r\n  final body = <String, dynamic>{};\r\n  if (title != null) body['title'] = title;\r\n  if (folderId != null) body['folder_id'] = folderId;\r\n  if (zoneId != null) body['zone_id'] = zoneId;\r\n  if (enabled != null) body['enabled'] = enabled;\r\n  final res = await http.patch(url, headers: await _authHeaders(), body: jsonEncode(body));\r\n  if (res.statusCode < 200 || res.statusCode >= 300) {\r\n    throw Exception('Failed to update announcement: ${res.body}');\r\n  }\r\n}\r\n\r\nFuture<void> deleteMusicFile(String id) async {\r\n  final res = await http.delete(Uri.parse('$apiBase/music/files/$id/'), headers: await _authHeaders());\r\n  if (res.statusCode < 200 || res.statusCode >= 300) throw Exception('Failed to delete music file');\r\n}\r\n\r\nFuture<void> deleteAnnouncementFile(String id) async {\r\n  final res = await http.delete(Uri.parse('$apiBase/announcements/$id/'), headers: await _authHeaders());\r\n  if (res.statusCode < 200 || res.statusCode >= 300) throw Exception('Failed to delete announcement');\r\n}\r\n\r\nFuture<void> deleteFolder(String id) async {\r\n  final res = await http.delete(Uri.parse('$apiBase/music/folders/$id/'), headers: await _authHeaders());\r\n  if (res.statusCode < 200 || res.statusCode >= 300) throw Exception('Failed to delete folder');\r\n}\r\n\r\nFuture<void> renameFolder(String id, String name) async {\r\n  final res = await http.patch(Uri.parse('$apiBase/music/folders/$id/'), headers: await _authHeaders(), body: jsonEncode({'name': name}));\r\n  if (res.statusCode < 200 || res.statusCode >= 300) throw Exception('Failed to rename folder');\r\n}\r\n\r\nFuture<void> deleteSchedule(String id) async {\r\n  final res = await http.delete(Uri.parse('$apiBase/schedules/schedules/$id/'), headers: await _authHeaders());\r\n  if (res.statusCode < 200 || res.statusCode >= 300) throw Exception('Failed to delete schedule');\r\n}\r\n\r\n// --- Zones & Devices ---";

if (c.includes(insertAfter)) {
  c = c.replace(insertAfter, replacement);
  console.log('api.dart: added delete/rename functions ✓');
} else {
  console.log('api.dart: pattern not found, appending at end');
  c += "\r\n\r\nFuture<void> deleteMusicFile(String id) async {\r\n  final res = await http.delete(Uri.parse('$apiBase/music/files/$id/'), headers: await _authHeaders());\r\n  if (res.statusCode < 200 || res.statusCode >= 300) throw Exception('Failed to delete music file');\r\n}\r\n\r\nFuture<void> deleteAnnouncementFile(String id) async {\r\n  final res = await http.delete(Uri.parse('$apiBase/announcements/$id/'), headers: await _authHeaders());\r\n  if (res.statusCode < 200 || res.statusCode >= 300) throw Exception('Failed to delete announcement');\r\n}\r\n\r\nFuture<void> deleteFolder(String id) async {\r\n  final res = await http.delete(Uri.parse('$apiBase/music/folders/$id/'), headers: await _authHeaders());\r\n  if (res.statusCode < 200 || res.statusCode >= 300) throw Exception('Failed to delete folder');\r\n}\r\n\r\nFuture<void> renameFolder(String id, String name) async {\r\n  final res = await http.patch(Uri.parse('$apiBase/music/folders/$id/'), headers: await _authHeaders(), body: jsonEncode({'name': name}));\r\n  if (res.statusCode < 200 || res.statusCode >= 300) throw Exception('Failed to rename folder');\r\n}\r\n\r\nFuture<void> deleteSchedule(String id) async {\r\n  final res = await http.delete(Uri.parse('$apiBase/schedules/schedules/$id/'), headers: await _authHeaders());\r\n  if (res.statusCode < 200 || res.statusCode >= 300) throw Exception('Failed to delete schedule');\r\n}\r\n";
}

fs.writeFileSync(p + '.tmp', c, 'utf8');
console.log('Written api.dart.tmp');

