# Generated by Django 5.0.1 on 2026-01-21 21:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('client', 'Client User'), ('floor_user', 'Floor User'), ('staff', 'sync2gear Staff'), ('admin', 'sync2gear Admin')], db_index=True, default='client', max_length=20)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('business_name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('subscription_tier', models.CharField(choices=[('basic', 'Basic'), ('professional', 'Professional'), ('enterprise', 'Enterprise')], db_index=True, default='basic', max_length=20)),
                ('subscription_status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled'), ('trial', 'Trial')], db_index=True, default='trial', max_length=20)),
                ('subscription_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('subscription_start', models.DateField(blank=True, null=True)),
                ('subscription_end', models.DateField(blank=True, null=True)),
                ('trial_days', models.IntegerField(default=14)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('stripe_customer_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=255)),
                ('premium_features', models.JSONField(blank=True, default=dict)),
                ('max_devices', models.IntegerField(default=5)),
                ('max_storage_gb', models.IntegerField(default=10)),
                ('max_floors', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'db_table': 'clients',
                'ordering': ['-created_at'],
            },
        ),
    ]
