# Generated by Django 4.2.27 on 2026-02-01 06:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInviteToken',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(db_index=True, max_length=255, unique=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('used', models.BooleanField(db_index=True, default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_invite_tokens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('client__isnull', True), ('floor__isnull', True), ('role__in', ['admin', 'staff'])), models.Q(('client__isnull', False), ('floor__isnull', True), ('role', 'client')), models.Q(('client__isnull', False), ('floor__isnull', False), ('role', 'floor_user')), _connector='OR'), name='valid_user_role_client_floor_combination'),
        ),
        migrations.AddField(
            model_name='userinvitetoken',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invite_token', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='userinvitetoken',
            index=models.Index(fields=['token', 'used'], name='user_invite_token_4ad85d_idx'),
        ),
        migrations.AddIndex(
            model_name='userinvitetoken',
            index=models.Index(fields=['expires_at'], name='user_invite_expires_48ddd7_idx'),
        ),
    ]
