# Generated by Django 5.0.1 on 2026-01-21 21:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('zones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelPlaylist',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('default_music_interval', models.IntegerField(default=15)),
                ('default_announcement_interval', models.IntegerField(default=30)),
                ('shuffle_music', models.BooleanField(default=False)),
                ('shuffle_announcements', models.BooleanField(default=False)),
                ('quiet_hours_start', models.TimeField(blank=True, null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, null=True)),
                ('enabled', models.BooleanField(db_index=True, default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_playlists', to='authentication.client')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_channel_playlists', to=settings.AUTH_USER_MODEL)),
                ('floors', models.ManyToManyField(blank=True, related_name='channel_playlists', to='zones.floor')),
                ('zones', models.ManyToManyField(blank=True, related_name='channel_playlists', to='zones.zone')),
            ],
            options={
                'db_table': 'channel_playlists',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ChannelPlaylistItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_type', models.CharField(choices=[('music', 'Music'), ('announcement', 'Announcement')], db_index=True, max_length=20)),
                ('content_id', models.UUIDField()),
                ('interval_minutes', models.IntegerField(blank=True, null=True)),
                ('fixed_times', models.JSONField(blank=True, default=list)),
                ('order', models.IntegerField(db_index=True, default=0)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='scheduler.channelplaylist')),
            ],
            options={
                'db_table': 'channel_playlist_items',
                'ordering': ['playlist', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('schedule_config', models.JSONField(default=dict)),
                ('priority', models.IntegerField(db_index=True, default=0)),
                ('enabled', models.BooleanField(db_index=True, default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='authentication.client')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_schedules', to=settings.AUTH_USER_MODEL)),
                ('devices', models.ManyToManyField(blank=True, related_name='schedules', to='zones.device')),
                ('zones', models.ManyToManyField(blank=True, related_name='schedules', to='zones.zone')),
            ],
            options={
                'db_table': 'schedules',
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='channelplaylist',
            index=models.Index(fields=['client', 'enabled'], name='channel_pla_client__d106cb_idx'),
        ),
        migrations.AddIndex(
            model_name='channelplaylistitem',
            index=models.Index(fields=['playlist', 'item_type'], name='channel_pla_playlis_8b4ae4_idx'),
        ),
        migrations.AddIndex(
            model_name='channelplaylistitem',
            index=models.Index(fields=['playlist', 'order'], name='channel_pla_playlis_22eccd_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['client', 'enabled'], name='schedules_client__6d12dc_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['enabled', 'priority'], name='schedules_enabled_1700af_idx'),
        ),
    ]
