# Generated by Django 4.2.27 on 2026-01-30 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['name']},
        ),
        migrations.RemoveIndex(
            model_name='schedule',
            name='schedules_enabled_1700af_idx',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='devices',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='priority',
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['enabled'], name='schedules_enabled_4c3ca0_idx'),
        ),
    ]
