# Generated by Django 4.2.27 on 2026-01-30 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_remove_priority_and_devices'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='last_executed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
