# Generated by Django 5.0.1 on 2026-01-21 21:31

import django.core.validators
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(db_index=True, max_length=50)),
                ('resource_type', models.CharField(db_index=True, max_length=50)),
                ('resource_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIProvider',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('provider_type', models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('google', 'Google Cloud'), ('elevenlabs', 'ElevenLabs')], db_index=True, max_length=20)),
                ('api_key', models.CharField(max_length=500)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('daily_request_limit', models.IntegerField(default=1000, validators=[django.core.validators.MinValueValidator(0)])),
                ('monthly_budget_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('requests_count', models.IntegerField(default=0)),
                ('tokens_used', models.BigIntegerField(default=0)),
                ('cost_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('features', models.JSONField(blank=True, default=list)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ai_providers',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['provider_type', 'is_active'], name='ai_provider_provide_b12c31_idx'), models.Index(fields=['is_active'], name='ai_provider_is_acti_a995cc_idx')],
            },
        ),
    ]
