# Generated by Django 4.2.27 on 2026-02-01 06:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0004_add_user_validation_and_invite_tokens'),
        ('admin_panel', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpersonationLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ended_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('actions_performed', models.JSONField(blank=True, default=list)),
                ('admin_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='impersonation_sessions', to=settings.AUTH_USER_MODEL)),
                ('impersonated_client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='impersonation_logs', to='authentication.client')),
            ],
            options={
                'db_table': 'impersonation_logs',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['admin_user', 'started_at'], name='impersonati_admin_u_c7b588_idx'), models.Index(fields=['impersonated_client', 'started_at'], name='impersonati_imperso_025c06_idx'), models.Index(fields=['started_at', 'ended_at'], name='impersonati_started_b614a9_idx')],
            },
        ),
    ]
