# Generated by Django 5.0.1 on 2026-01-21 21:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_premium', models.BooleanField(db_index=True, default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='authentication.client')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_floors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'floors',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('default_volume', models.IntegerField(default=70)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='authentication.client')),
                ('floor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='zones.floor')),
            ],
            options={
                'db_table': 'zones',
                'ordering': ['floor', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('device_type', models.CharField(max_length=50)),
                ('device_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('firmware_version', models.CharField(blank=True, max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('last_seen', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_online', models.BooleanField(db_index=True, default=False)),
                ('volume', models.IntegerField(default=70)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='authentication.client')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='zones.zone')),
            ],
            options={
                'db_table': 'devices',
                'ordering': ['zone', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='floor',
            index=models.Index(fields=['client', 'is_premium'], name='floors_client__0e29aa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='floor',
            unique_together={('client', 'name')},
        ),
        migrations.AddIndex(
            model_name='zone',
            index=models.Index(fields=['client', 'is_active'], name='zones_client__3fbe54_idx'),
        ),
        migrations.AddIndex(
            model_name='zone',
            index=models.Index(fields=['floor', 'is_active'], name='zones_floor_i_31cd18_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='zone',
            unique_together={('client', 'name')},
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['device_id'], name='devices_device__c4b5e4_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['client', 'is_online'], name='devices_client__4c4627_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['zone', 'is_online'], name='devices_zone_id_c719e4_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['last_seen'], name='devices_last_se_cc30d3_idx'),
        ),
    ]
