import { User, Client, Device, Folder, MusicFile, AnnouncementScript, AnnouncementAudio, Schedule, PlayEvent, AuditLog, ChannelPlaylist, Floor } from './types';

// Mock data for development
export const mockUsers: User[] = [
  {
    id: 'user1',
    email: 'admin@sync2gear.com',
    name: 'Admin User',
    role: 'admin',
    createdAt: new Date('2025-01-01'),
    lastSeen: new Date(),
  },
  {
    id: 'user2',
    email: 'client1@example.com',
    name: 'Coffee Shop Manager',
    role: 'client',
    clientId: 'client1',
    createdAt: new Date('2025-01-05'),
    lastSeen: new Date(),
  },
  {
    id: 'user3',
    email: 'floor1@downtowncoffee.com',
    name: 'Ground Floor Staff',
    role: 'floor_user',
    clientId: 'client1',
    floorId: 'floor1', // Restricted to Ground Floor only
    createdAt: new Date('2025-01-12'),
    lastSeen: new Date(),
  },
];

export const mockClients: Client[] = [
  {
    id: 'client1',
    name: 'Downtown Coffee Shop',
    businessName: 'Downtown Coffee Ltd',
    email: 'manager@downtowncoffee.com',
    telephone: '+44 20 1234 5678',
    description: 'Independent coffee shop serving specialty coffee and pastries',
    status: 'active',
    trialDays: 0,
    subscriptionPrice: 49.99,
    subscriptionStatus: 'active',
    stripeCustomerId: 'cus_mock123',
    stripeSubscriptionId: 'sub_mock123',
    premiumFeatures: {
      multiFloor: false, // Basic plan - 1 floor only
      aiCredits: 75, // Low on credits
      maxFloors: 1,
    },
    createdAt: new Date('2025-01-05'),
    updatedAt: new Date('2025-01-05'),
  },
  {
    id: 'client2',
    name: 'Retail Store Chain',
    businessName: 'Retail Ventures PLC',
    email: 'it@retailchain.co.uk',
    telephone: '+44 20 9876 5432',
    description: 'Multi-location retail chain with 15 stores across the UK',
    status: 'active',
    trialDays: 0,
    subscriptionPrice: 199.99,
    subscriptionStatus: 'active',
    stripeCustomerId: 'cus_mock456',
    stripeSubscriptionId: 'sub_mock456',
    premiumFeatures: {
      multiFloor: true, // Premium plan - unlimited floors
      aiCredits: 450, // Healthy credit balance
      maxFloors: 999, // Unlimited
    },
    createdAt: new Date('2025-01-10'),
    updatedAt: new Date('2025-01-10'),
  },
];

export const mockDevices: Device[] = [
  {
    id: 'device1',
    name: 'Main Floor Speaker',
    clientId: 'client1',
    status: 'online',
    lastSeen: new Date(),
    zone: 'Ground Floor',
  },
  {
    id: 'device2',
    name: 'Upstairs Speaker',
    clientId: 'client1',
    status: 'online',
    lastSeen: new Date(Date.now() - 30000),
    zone: 'First Floor',
  },
  {
    id: 'device3',
    name: 'Outdoor Speaker',
    clientId: 'client1',
    status: 'offline',
    lastSeen: new Date(Date.now() - 3600000),
    zone: 'Outdoor',
  },
];

export const mockFloors: Floor[] = [
  {
    id: 'floor1',
    name: 'Ground Floor',
    clientId: 'client1',
    description: 'Main customer service area with seating',
    deviceIds: ['device1'],
    isPremium: false, // First floor is included in basic plan
    createdAt: new Date('2025-01-05'),
    createdBy: 'user2',
  },
  {
    id: 'floor2',
    name: 'First Floor',
    clientId: 'client1',
    description: 'Additional seating area upstairs',
    deviceIds: ['device2'],
    isPremium: true, // Additional floor would require premium
    createdAt: new Date('2025-01-06'),
    createdBy: 'user2',
  },
  {
    id: 'floor3',
    name: 'Outdoor Patio',
    clientId: 'client1',
    description: 'Seasonal outdoor seating',
    deviceIds: ['device3'],
    isPremium: true,
    createdAt: new Date('2025-01-07'),
    createdBy: 'user2',
  },
];

export const mockFolders: Folder[] = [
  {
    id: 'folder1',
    name: 'Jazz Collection',
    clientId: 'client1',
    type: 'music',
    createdAt: new Date('2025-01-06'),
    createdBy: 'user2',
  },
  {
    id: 'folder2',
    name: 'Pop Hits',
    clientId: 'client1',
    type: 'music',
    createdAt: new Date('2025-01-06'),
    createdBy: 'user2',
  },
  {
    id: 'folder3',
    name: 'Promotional',
    clientId: 'client1',
    type: 'announcements',
    createdAt: new Date('2025-01-07'),
    createdBy: 'user2',
  },
];

export const mockMusicFiles: MusicFile[] = [
  {
    id: 'music1',
    name: 'Autumn Leaves.mp3',
    folderId: 'folder1',
    clientId: 'client1',
    url: '#',
    size: 4500000,
    duration: 245,
    type: 'audio/mpeg',
    createdAt: new Date('2025-01-06'),
    createdBy: 'user2',
  },
  {
    id: 'music2',
    name: 'Take Five.mp3',
    folderId: 'folder1',
    clientId: 'client1',
    url: '#',
    size: 5200000,
    duration: 324,
    type: 'audio/mpeg',
    createdAt: new Date('2025-01-06'),
    createdBy: 'user2',
  },
  {
    id: 'music3',
    name: 'Summer Vibes.mp3',
    folderId: 'folder2',
    clientId: 'client1',
    url: '#',
    size: 3800000,
    duration: 198,
    type: 'audio/mpeg',
    createdAt: new Date('2025-01-06'),
    createdBy: 'user2',
  },
];

// Extended music queue with images and categories
export const mockMusicQueue = [
  {
    id: 'music1',
    title: 'Focus Flow',
    artist: 'Productivity Sounds',
    duration: 245,
    category: 'Self Improvement',
    image: 'https://images.unsplash.com/photo-1499336315816-097655dcfbda?w=400',
  },
  {
    id: 'music2',
    title: 'Business Mindset',
    artist: 'Success Tracks',
    duration: 324,
    category: 'Business',
    image: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=400',
  },
  {
    id: 'music3',
    title: 'Learning Zone',
    artist: 'Study Music Co',
    duration: 198,
    category: 'Learning',
    image: 'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=400',
  },
  {
    id: 'music4',
    title: 'Mindful Meditation',
    artist: 'Calm Collective',
    duration: 412,
    category: 'Self Improvement',
    image: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=400',
  },
  {
    id: 'music5',
    title: 'Startup Energy',
    artist: 'Business Beats',
    duration: 287,
    category: 'Business',
    image: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=400',
  },
  {
    id: 'music6',
    title: 'Study Sessions',
    artist: 'Learning Lab',
    duration: 356,
    category: 'Learning',
    image: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=400',
  },
];

export const mockAnnouncementScripts: AnnouncementScript[] = [
  {
    id: 'script1',
    title: 'Daily Special',
    text: 'Try our delicious coffee special of the day. Available now at the counter.',
    clientId: 'client1',
    folderId: 'folder3',
    enabled: true,
    category: 'promotion',
    createdAt: new Date('2025-01-07'),
    createdBy: 'user2',
  },
  {
    id: 'script2',
    title: 'Closing Soon',
    text: 'We will be closing in 30 minutes. Thank you for visiting us today.',
    clientId: 'client1',
    folderId: 'folder3',
    enabled: true,
    category: 'operational',
    createdAt: new Date('2025-01-07'),
    createdBy: 'user2',
  },
];

export const mockAnnouncementAudio: AnnouncementAudio[] = [
  {
    id: 'audio1',
    title: 'Daily Special',
    scriptId: 'script1',
    clientId: 'client1',
    folderId: 'folder3',
    url: '#',
    duration: 12,
    type: 'tts',
    enabled: true,
    category: 'promotion',
    createdAt: new Date('2025-01-07'),
    createdBy: 'user2',
  },
  {
    id: 'audio2',
    title: 'Closing Soon',
    scriptId: 'script2',
    clientId: 'client1',
    folderId: 'folder3',
    url: '#',
    duration: 8,
    type: 'tts',
    enabled: true,
    category: 'operational',
    createdAt: new Date('2025-01-07'),
    createdBy: 'user2',
  },
];

// Pre-made announcement templates by sync2gear
export interface AnnouncementTemplate {
  id: string;
  title: string;
  description: string;
  category: 'retail' | 'restaurant' | 'office' | 'healthcare' | 'gym' | 'general';
  image: string;
  script: string;
  duration: number;
  voiceType: 'professional' | 'friendly' | 'energetic' | 'calm';
  availableFor: 'all' | string[]; // 'all' or array of client IDs
  createdBy: string; // sync2gear admin ID
  createdAt: Date;
  updatedAt: Date;
  active: boolean;
}

// Template folders containing multiple announcements
export interface AnnouncementTemplateFolder {
  id: string;
  name: string;
  description: string;
  category: 'retail' | 'restaurant' | 'office' | 'healthcare' | 'gym' | 'general';
  image: string;
  templates: AnnouncementTemplate[];
  availableFor: 'all' | string[];
  active: boolean;
  createdBy: string;
  createdAt: Date;
  updatedAt: Date;
}

export const mockAnnouncementTemplates: AnnouncementTemplate[] = [
  {
    id: 'template1',
    title: 'Welcome Message',
    description: 'Friendly welcome for customers entering your store',
    category: 'retail',
    image: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=400&h=300&fit=crop',
    script: 'Welcome! Thank you for visiting us today. Our team is here to help you find exactly what you need. Enjoy your shopping experience!',
    duration: 15,
    voiceType: 'friendly',
    availableFor: 'all',
    createdBy: 'user1',
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
    active: true,
  },
  {
    id: 'template2',
    title: 'Flash Sale Alert',
    description: 'Announce limited-time offers and flash sales',
    category: 'retail',
    image: 'https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?w=400&h=300&fit=crop',
    script: 'Attention shoppers! Flash sale happening now! Get 30% off selected items for the next hour only. Head to our featured section to discover amazing deals!',
    duration: 18,
    voiceType: 'energetic',
    availableFor: 'all',
    createdBy: 'user1',
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-10'),
    active: true,
  },
  {
    id: 'template3',
    title: 'Lunch Special',
    description: 'Daily lunch menu announcement for restaurants',
    category: 'restaurant',
    image: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=400&h=300&fit=crop',
    script: 'Todays lunch special features our signature pasta with fresh seasonal vegetables, served with artisan bread. Available until 3 PM. Ask your server for details!',
    script: "Today's lunch special features our chef's signature pasta with fresh seasonal vegetables, served with artisan bread. Available until 3 PM. Ask your server for details!",
    duration: 16,
    voiceType: 'professional',
    availableFor: 'all',
    createdBy: 'user1',
    createdAt: new Date('2025-01-02'),
    updatedAt: new Date('2025-01-02'),
    active: true,
  },
  {
    id: 'template4',
    title: 'Table Ready',
    description: 'Notify customers when their table is ready',
    category: 'restaurant',
    image: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=400&h=300&fit=crop',
    script: 'Attention guests: Your table is now ready. Please proceed to the host stand with your number. Thank you for your patience!',
    duration: 12,
    voiceType: 'professional',
    availableFor: 'all',
    createdBy: 'user1',
    createdAt: new Date('2025-01-02'),
    updatedAt: new Date('2025-01-02'),
    active: true,
  },
  {
    id: 'template5',
    title: 'Hand Hygiene Reminder',
    description: 'Healthcare facility hygiene announcement',
    category: 'healthcare',
    image: 'https://images.unsplash.com/photo-1584982751601-97dcc096659c?w=400&h=300&fit=crop',
    script: 'Please remember to sanitize your hands using the dispensers located throughout the facility. Your health and safety are our top priority. Thank you for your cooperation.',
    duration: 14,
    voiceType: 'calm',
    availableFor: 'all',
    createdBy: 'user1',
    createdAt: new Date('2025-01-03'),
    updatedAt: new Date('2025-01-03'),
    active: true,
  },
  {
    id: 'template6',
    title: 'Class Starting Soon',
    description: 'Gym class reminder announcement',
    category: 'gym',
    image: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=400&h=300&fit=crop',
    script: 'Attention members: The yoga class will begin in 5 minutes in Studio A. Please bring your mat and water bottle. All fitness levels welcome!',
    duration: 13,
    voiceType: 'energetic',
    availableFor: 'all',
    createdBy: 'user1',
    createdAt: new Date('2025-01-04'),
    updatedAt: new Date('2025-01-04'),
    active: true,
  },
  {
    id: 'template7',
    title: 'Office Meeting Reminder',
    description: 'Conference room meeting notification',
    category: 'office',
    image: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=400&h=300&fit=crop',
    script: 'Reminder: The team meeting will commence in 10 minutes in Conference Room B. Please gather your materials and join us promptly. Thank you.',
    duration: 13,
    voiceType: 'professional',
    availableFor: 'all',
    createdBy: 'user1',
    createdAt: new Date('2025-01-05'),
    updatedAt: new Date('2025-01-05'),
    active: true,
  },
  {
    id: 'template8',
    title: 'Closing Time',
    description: 'Store closing announcement',
    category: 'general',
    image: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=400&h=300&fit=crop',
    script: 'Attention: We will be closing in 15 minutes. Please bring your final selections to the checkout. We appreciate your business and look forward to seeing you again soon!',
    duration: 16,
    voiceType: 'friendly',
    availableFor: 'all',
    createdBy: 'user1',
    createdAt: new Date('2025-01-06'),
    updatedAt: new Date('2025-01-06'),
    active: true,
  },
  {
    id: 'template9',
    title: 'Fire Drill Announcement',
    description: 'Safety drill notification',
    category: 'office',
    image: 'https://images.unsplash.com/photo-1509281373149-e957c6296406?w=400&h=300&fit=crop',
    script: 'This is a fire drill. Please calmly evacuate the building using the nearest exit. Do not use elevators. Proceed to the designated assembly point. This is a drill.',
    duration: 15,
    voiceType: 'calm',
    availableFor: 'all',
    createdBy: 'user1',
    createdAt: new Date('2025-01-07'),
    updatedAt: new Date('2025-01-07'),
    active: true,
  },
  {
    id: 'template10',
    title: 'Happy Hour',
    description: 'Bar and restaurant happy hour promotion',
    category: 'restaurant',
    image: 'https://images.unsplash.com/photo-1514933651103-005eec06c04b?w=400&h=300&fit=crop',
    script: 'Happy hour is now in full swing! Enjoy half-price appetizers and specialty cocktails until 7 PM. Join us at the bar for todays featured drinks. Cheers!',
    script: "Happy hour is now in full swing! Enjoy half-price appetizers and specialty cocktails until 7 PM. Join us at the bar for today's featured drinks. Cheers!",
    duration: 14,
    voiceType: 'energetic',
    availableFor: 'all',
    createdBy: 'user1',
    createdAt: new Date('2025-01-08'),
    updatedAt: new Date('2025-01-08'),
    active: true,
  },
  {
    id: 'template11',
    title: 'Lost Child',
    description: 'Emergency lost child announcement',
    category: 'retail',
    image: 'https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?w=400&h=300&fit=crop',
    script: 'Attention: A young child is waiting at customer service. If you are missing your child, please come to the customer service desk immediately. Thank you.',
    duration: 12,
    voiceType: 'calm',
    availableFor: 'all',
    createdBy: 'user1',
    createdAt: new Date('2025-01-09'),
    updatedAt: new Date('2025-01-09'),
    active: true,
  },
  {
    id: 'template12',
    title: 'Weekend Sale',
    description: 'Weekend promotional announcement',
    category: 'retail',
    image: 'https://images.unsplash.com/photo-1472851294608-062f824d29cc?w=400&h=300&fit=crop',
    script: 'This weekend only! Take advantage of our storewide sale with up to 50% off. From clothing to electronics, we have got incredible deals throughout the store. Do not miss out!',
    script: "This weekend only! Take advantage of our storewide sale with up to 50% off. From clothing to electronics, we've got incredible deals throughout the store. Don't miss out!",
    duration: 17,
    voiceType: 'energetic',
    availableFor: 'all',
    createdBy: 'user1',
    createdAt: new Date('2025-01-10'),
    updatedAt: new Date('2025-01-10'),
    active: true,
  },
];

export const mockAnnouncementTemplateFolders: AnnouncementTemplateFolder[] = [
  {
    id: 'folder1',
    name: 'Retail Essentials Pack',
    description: 'Complete set of retail store announcements',
    category: 'retail',
    image: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=400&h=300&fit=crop',
    templates: [
      {
        id: 'rf1-1',
        title: 'Welcome Message',
        description: 'Friendly welcome for customers',
        category: 'retail',
        image: '',
        script: 'Welcome! Thank you for visiting us today. Our team is here to help you find exactly what you need. Enjoy your shopping experience!',
        duration: 15,
        voiceType: 'friendly',
        availableFor: 'all',
        createdBy: 'user1',
        createdAt: new Date('2025-01-01'),
        updatedAt: new Date('2025-01-01'),
        active: true,
      },
      {
        id: 'rf1-2',
        title: 'Flash Sale Alert',
        description: 'Limited-time offer announcement',
        category: 'retail',
        image: '',
        script: 'Attention shoppers! Flash sale happening now! Get 30% off selected items for the next hour only. Head to our featured section to discover amazing deals!',
        duration: 18,
        voiceType: 'energetic',
        availableFor: 'all',
        createdBy: 'user1',
        createdAt: new Date('2025-01-01'),
        updatedAt: new Date('2025-01-01'),
        active: true,
      },
      {
        id: 'rf1-3',
        title: 'Weekend Sale',
        description: 'Weekend promotional announcement',
        category: 'retail',
        image: '',
        script: 'This weekend only! Take advantage of our storewide sale with up to 50% off. From clothing to electronics, we have got incredible deals throughout the store. Do not miss out!',
        script: "This weekend only! Take advantage of our storewide sale with up to 50% off. From clothing to electronics, we've got incredible deals throughout the store. Don't miss out!",
        duration: 17,
        voiceType: 'energetic',
        availableFor: 'all',
        createdBy: 'user1',
        createdAt: new Date('2025-01-01'),
        updatedAt: new Date('2025-01-01'),
        active: true,
      },
      {
        id: 'rf1-4',
        title: 'Closing Time',
        description: 'Store closing reminder',
        category: 'retail',
        image: '',
        script: 'Attention: We will be closing in 15 minutes. Please bring your final selections to the checkout. We appreciate your business and look forward to seeing you again soon!',
        duration: 16,
        voiceType: 'friendly',
        availableFor: 'all',
        createdBy: 'user1',
        createdAt: new Date('2025-01-01'),
        updatedAt: new Date('2025-01-01'),
        active: true,
      },
      {
        id: 'rf1-5',
        title: 'Fitting Room Policy',
        description: 'Fitting room guidelines',
        category: 'retail',
        image: '',
        script: 'Reminder: Our fitting rooms have a 6-item limit. Please check with our staff if you need assistance with sizing. Thank you for your cooperation.',
        duration: 13,
        voiceType: 'professional',
        availableFor: 'all',
        createdBy: 'user1',
        createdAt: new Date('2025-01-01'),
        updatedAt: new Date('2025-01-01'),
        active: true,
      },
      {
        id: 'rf1-6',
        title: 'New Arrivals',
        description: 'New product announcement',
        category: 'retail',
        image: '',
        script: 'Check out our new arrivals! Fresh styles just in from top brands. Visit our featured displays to see the latest trends for this season.',
        duration: 14,
        voiceType: 'energetic',
        availableFor: 'all',
        createdBy: 'user1',
        createdAt: new Date('2025-01-01'),
        updatedAt: new Date('2025-01-01'),
        active: true,
      },
      {
        id: 'rf1-7',
        title: 'Customer Service',
        description: 'Customer service location',
        category: 'retail',
        image: '',
        script: 'Need assistance? Our customer service desk is located at the front of the store. Our team is happy to help with returns, exchanges, and any questions you may have.',
        duration: 15,
        voiceType: 'friendly',
        availableFor: 'all',
        createdBy: 'user1',
        createdAt: new Date('2025-01-01'),
        updatedAt: new Date('2025-01-01'),
        active: true,
      },
      {
        id: 'rf1-8',
        title: 'Lost Child Protocol',
        description: 'Emergency lost child announcement',
        category: 'retail',
        image: '',
        script: 'Attention: A young child is waiting at customer service. If you are missing your child, please come to the customer service desk immediately. Thank you.',
        duration: 12,
        voiceType: 'calm',
        availableFor: 'all',
        createdBy: 'user1',
        createdAt: new Date('2025-01-01'),
        updatedAt: new Date('2025-01-01'),
        active: true,
      },
    ],
    availableFor: 'all',
    active: true,
    createdBy: 'user1',
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },
  {
    id: 'folder2',
    name: 'Restaurant Service Pack',
    description: 'Essential announcements for dining establishments',
    category: 'restaurant',
    image: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=400&h=300&fit=crop',
    templates: [
      {
        id: 'rf2-1',
        title: 'Daily Special',
        description: 'Daily menu special announcement',
        category: 'restaurant',
        image: '',
        script: 'Todays special features our signature dish with fresh seasonal ingredients. Ask your server for details and pairing recommendations!',
        script: "Today's special features our chef's signature dish with fresh seasonal ingredients. Ask your server for details and pairing recommendations!",
        duration: 14,
        voiceType: 'professional',
        availableFor: 'all',
        createdBy: 'user1',
        createdAt: new Date('2025-01-02'),
        updatedAt: new Date('2025-01-02'),
        active: true,
      },
      {
        id: 'rf2-2',
        title: 'Table Ready',
        description: 'Table ready notification',
        category: 'restaurant',
        image: '',
        script: 'Attention guests: Your table is now ready. Please proceed to the host stand with your number. Thank you for your patience!',
        duration: 12,
        voiceType: 'professional',
        availableFor: 'all',
        createdBy: 'user1',
        createdAt: new Date('2025-01-02'),
        updatedAt: new Date('2025-01-02'),
        active: true,
      },
      {
        id: 'rf2-3',
        title: 'Happy Hour',
        description: 'Happy hour promotion',
        category: 'restaurant',
        image: '',
        script: 'Happy hour is now in full swing! Enjoy half-price appetizers and specialty cocktails until 7 PM. Join us at the bar for todays featured drinks. Cheers!',
        script: "Happy hour is now in full swing! Enjoy half-price appetizers and specialty cocktails until 7 PM. Join us at the bar for today's featured drinks. Cheers!",
        duration: 14,
        voiceType: 'energetic',
        availableFor: 'all',
        createdBy: 'user1',
        createdAt: new Date('2025-01-02'),
        updatedAt: new Date('2025-01-02'),
        active: true,
      },
      {
        id: 'rf2-4',
        title: 'Kitchen Closing',
        description: 'Last orders announcement',
        category: 'restaurant',
        image: '',
        script: 'Last call for food orders! Our kitchen will be closing in 15 minutes. Please place your final orders now. Thank you!',
        duration: 11,
        voiceType: 'professional',
        availableFor: 'all',
        createdBy: 'user1',
        createdAt: new Date('2025-01-02'),
        updatedAt: new Date('2025-01-02'),
        active: true,
      },
      {
        id: 'rf2-5',
        title: 'Reservation Reminder',
        description: 'Upcoming reservation notice',
        category: 'restaurant',
        image: '',
        script: 'Reminder for party of four under the name Smith: Your reservation is in 15 minutes. Please check in at the host stand when you arrive.',
        duration: 13,
        voiceType: 'professional',
        availableFor: 'all',
        createdBy: 'user1',
        createdAt: new Date('2025-01-02'),
        updatedAt: new Date('2025-01-02'),
        active: true,
      },
      {
        id: 'rf2-6',
        title: 'Live Music',
        description: 'Live entertainment announcement',
        category: 'restaurant',
        image: '',
        script: 'Enjoy live music tonight starting at 8 PM! Join us for great food, drinks, and entertainment in our lounge area.',
        duration: 12,
        voiceType: 'energetic',
        availableFor: 'all',
        createdBy: 'user1',
        createdAt: new Date('2025-01-02'),
        updatedAt: new Date('2025-01-02'),
        active: true,
      },
    ],
    availableFor: 'all',
    active: true,
    createdBy: 'user1',
    createdAt: new Date('2025-01-02'),
    updatedAt: new Date('2025-01-02'),
  },
  {
    id: 'folder3',
    name: 'Gym & Fitness Collection',
    description: 'Motivational and operational announcements for fitness centers',
    category: 'gym',
    image: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=400&h=300&fit=crop',
    templates: [
      {
        id: 'rf3-1',
        title: 'Class Starting Soon',
        description: 'Class reminder',
        category: 'gym',
        image: '',
        script: 'Attention members: The yoga class will begin in 5 minutes in Studio A. Please bring your mat and water bottle. All fitness levels welcome!',
        duration: 13,
        voiceType: 'energetic',
        availableFor: 'all',
        createdBy: 'user1',
        createdAt: new Date('2025-01-04'),
        updatedAt: new Date('2025-01-04'),
        active: true,
      },
      {
        id: 'rf3-2',
        title: 'Hydration Reminder',
        description: 'Stay hydrated message',
        category: 'gym',
        image: '',
        script: 'Remember to stay hydrated! Water stations are located throughout the facility. Keep pushing, you are doing great!',
        duration: 11,
        voiceType: 'energetic',
        availableFor: 'all',
        createdBy: 'user1',
        createdAt: new Date('2025-01-04'),
        updatedAt: new Date('2025-01-04'),
        active: true,
      },
      {
        id: 'rf3-3',
        title: 'Equipment Wipe Down',
        description: 'Equipment cleaning reminder',
        category: 'gym',
        image: '',
        script: 'Please remember to wipe down equipment after use. Cleaning stations are conveniently located around the gym. Thank you for helping us keep our facility clean!',
        duration: 14,
        voiceType: 'friendly',
        availableFor: 'all',
        createdBy: 'user1',
        createdAt: new Date('2025-01-04'),
        updatedAt: new Date('2025-01-04'),
        active: true,
      },
      {
        id: 'rf3-4',
        title: 'New Class Schedule',
        description: 'Class schedule update',
        category: 'gym',
        image: '',
        script: 'Check out our new class schedule at the front desk! We have added early morning and evening sessions to fit your busy lifestyle.',
        duration: 12,
        voiceType: 'energetic',
        availableFor: 'all',
        createdBy: 'user1',
        createdAt: new Date('2025-01-04'),
        updatedAt: new Date('2025-01-04'),
        active: true,
      },
      {
        id: 'rf3-5',
        title: 'Personal Training',
        description: 'PT services promotion',
        category: 'gym',
        image: '',
        script: 'Want to reach your fitness goals faster? Ask about our personal training packages at the front desk. First session is complimentary!',
        duration: 13,
        voiceType: 'energetic',
        availableFor: 'all',
        createdBy: 'user1',
        createdAt: new Date('2025-01-04'),
        updatedAt: new Date('2025-01-04'),
        active: true,
      },
    ],
    availableFor: 'all',
    active: true,
    createdBy: 'user1',
    createdAt: new Date('2025-01-04'),
    updatedAt: new Date('2025-01-04'),
  },
  {
    id: 'folder4',
    name: 'Healthcare Facility Suite',
    description: 'Professional healthcare environment announcements',
    category: 'healthcare',
    image: 'https://images.unsplash.com/photo-1584982751601-97dcc096659c?w=400&h=300&fit=crop',
    templates: [
      {
        id: 'rf4-1',
        title: 'Hand Hygiene',
        description: 'Hygiene reminder',
        category: 'healthcare',
        image: '',
        script: 'Please remember to sanitize your hands using the dispensers located throughout the facility. Your health and safety are our top priority. Thank you for your cooperation.',
        duration: 14,
        voiceType: 'calm',
        availableFor: 'all',
        createdBy: 'user1',
        createdAt: new Date('2025-01-03'),
        updatedAt: new Date('2025-01-03'),
        active: true,
      },
      {
        id: 'rf4-2',
        title: 'Patient Call',
        description: 'Patient ready notification',
        category: 'healthcare',
        image: '',
        script: 'Patient Smith, please proceed to room 3. Dr. Johnson is ready to see you now.',
        duration: 8,
        voiceType: 'professional',
        availableFor: 'all',
        createdBy: 'user1',
        createdAt: new Date('2025-01-03'),
        updatedAt: new Date('2025-01-03'),
        active: true,
      },
      {
        id: 'rf4-3',
        title: 'Visiting Hours',
        description: 'Visitor guidelines',
        category: 'healthcare',
        image: '',
        script: 'Reminder: Visiting hours end in 30 minutes. Please complete your visits and check out at the reception desk. Thank you.',
        duration: 11,
        voiceType: 'calm',
        availableFor: 'all',
        createdBy: 'user1',
        createdAt: new Date('2025-01-03'),
        updatedAt: new Date('2025-01-03'),
        active: true,
      },
      {
        id: 'rf4-4',
        title: 'Quiet Hours',
        description: 'Quiet time reminder',
        category: 'healthcare',
        image: '',
        script: 'Quiet hours are now in effect. Please keep voices low and silence mobile devices. Thank you for respecting our patients recovery time.',
        duration: 12,
        voiceType: 'calm',
        availableFor: 'all',
        createdBy: 'user1',
        createdAt: new Date('2025-01-03'),
        updatedAt: new Date('2025-01-03'),
        active: true,
      },
    ],
    availableFor: 'all',
    active: true,
    createdBy: 'user1',
    createdAt: new Date('2025-01-03'),
    updatedAt: new Date('2025-01-03'),
  },
  {
    id: 'folder5',
    name: 'Office Environment Pack',
    description: 'Professional workplace announcements and reminders',
    category: 'office',
    image: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=400&h=300&fit=crop',
    templates: [
      {
        id: 'rf5-1',
        title: 'Meeting Reminder',
        description: 'Meeting notification',
        category: 'office',
        image: '',
        script: 'Reminder: The team meeting will commence in 10 minutes in Conference Room B. Please gather your materials and join us promptly. Thank you.',
        duration: 13,
        voiceType: 'professional',
        availableFor: 'all',
        createdBy: 'user1',
        createdAt: new Date('2025-01-05'),
        updatedAt: new Date('2025-01-05'),
        active: true,
      },
      {
        id: 'rf5-2',
        title: 'Fire Drill',
        description: 'Emergency drill announcement',
        category: 'office',
        image: '',
        script: 'This is a fire drill. Please calmly evacuate the building using the nearest exit. Do not use elevators. Proceed to the designated assembly point. This is a drill.',
        duration: 15,
        voiceType: 'calm',
        availableFor: 'all',
        createdBy: 'user1',
        createdAt: new Date('2025-01-05'),
        updatedAt: new Date('2025-01-05'),
        active: true,
      },
      {
        id: 'rf5-3',
        title: 'Lunch Break',
        description: 'Break time reminder',
        category: 'office',
        image: '',
        script: 'Reminder: The cafeteria is now open for lunch. Todays specials are posted at the entrance. Enjoy your meal!',
        duration: 10,
        voiceType: 'friendly',
        availableFor: 'all',
        createdBy: 'user1',
        createdAt: new Date('2025-01-05'),
        updatedAt: new Date('2025-01-05'),
        active: true,
      },
      {
        id: 'rf5-4',
        title: 'Visitor Arrival',
        description: 'Guest notification',
        category: 'office',
        image: '',
        script: 'Attention: Your visitor has arrived and is waiting in the reception area. Please come to the front desk to escort your guest.',
        duration: 11,
        voiceType: 'professional',
        availableFor: 'all',
        createdBy: 'user1',
        createdAt: new Date('2025-01-05'),
        updatedAt: new Date('2025-01-05'),
        active: true,
      },
      {
        id: 'rf5-5',
        title: 'IT Maintenance',
        description: 'System maintenance notice',
        category: 'office',
        image: '',
        script: 'Attention: IT will be performing system maintenance in 15 minutes. Please save your work and log off when convenient. Service will resume shortly.',
        duration: 14,
        voiceType: 'professional',
        availableFor: 'all',
        createdBy: 'user1',
        createdAt: new Date('2025-01-05'),
        updatedAt: new Date('2025-01-05'),
        active: true,
      },
    ],
    availableFor: 'all',
    active: true,
    createdBy: 'user1',
    createdAt: new Date('2025-01-05'),
    updatedAt: new Date('2025-01-05'),
  },
  {
    id: 'folder6',
    name: 'General Purpose Collection',
    description: 'Versatile announcements for any business type',
    category: 'general',
    image: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=400&h=300&fit=crop',
    templates: [
      {
        id: 'rf6-1',
        title: 'Opening Soon',
        description: 'Opening time announcement',
        category: 'general',
        image: '',
        script: 'We will be opening in 10 minutes. Thank you for waiting. We look forward to serving you!',
        duration: 9,
        voiceType: 'friendly',
        availableFor: 'all',
        createdBy: 'user1',
        createdAt: new Date('2025-01-06'),
        updatedAt: new Date('2025-01-06'),
        active: true,
      },
      {
        id: 'rf6-2',
        title: 'Closing Soon',
        description: 'Closing time reminder',
        category: 'general',
        image: '',
        script: 'Attention: We will be closing in 15 minutes. Please complete your visit and proceed to the exit. Thank you for visiting us today!',
        duration: 13,
        voiceType: 'friendly',
        availableFor: 'all',
        createdBy: 'user1',
        createdAt: new Date('2025-01-06'),
        updatedAt: new Date('2025-01-06'),
        active: true,
      },
      {
        id: 'rf6-3',
        title: 'WiFi Information',
        description: 'Guest WiFi details',
        category: 'general',
        image: '',
        script: 'Free WiFi is available for our guests. Connect to "Guest Network" and ask staff for the password. Enjoy!',
        duration: 10,
        voiceType: 'friendly',
        availableFor: 'all',
        createdBy: 'user1',
        createdAt: new Date('2025-01-06'),
        updatedAt: new Date('2025-01-06'),
        active: true,
      },
      {
        id: 'rf6-4',
        title: 'Lost and Found',
        description: 'Lost items announcement',
        category: 'general',
        image: '',
        script: 'If you have lost an item, please check with our reception desk. We maintain a lost and found service for your convenience.',
        duration: 11,
        voiceType: 'professional',
        availableFor: 'all',
        createdBy: 'user1',
        createdAt: new Date('2025-01-06'),
        updatedAt: new Date('2025-01-06'),
        active: true,
      },
      {
        id: 'rf6-5',
        title: 'Weather Alert',
        description: 'Weather condition notice',
        category: 'general',
        image: '',
        script: 'Weather advisory: Heavy rain is expected this afternoon. Please take care when leaving and watch your step. Umbrellas are available at the entrance.',
        duration: 13,
        voiceType: 'calm',
        availableFor: 'all',
        createdBy: 'user1',
        createdAt: new Date('2025-01-06'),
        updatedAt: new Date('2025-01-06'),
        active: true,
      },
      {
        id: 'rf6-6',
        title: 'Thank You Message',
        description: 'Customer appreciation',
        category: 'general',
        image: '',
        script: 'Thank you for choosing us! Your support means everything to our team. We hope to see you again soon!',
        duration: 10,
        voiceType: 'friendly',
        availableFor: 'all',
        createdBy: 'user1',
        createdAt: new Date('2025-01-06'),
        updatedAt: new Date('2025-01-06'),
        active: true,
      },
    ],
    availableFor: 'all',
    active: true,
    createdBy: 'user1',
    createdAt: new Date('2025-01-06'),
    updatedAt: new Date('2025-01-06'),
  },
];

export interface MusicTemplate {
  id: string;
  title: string;
  description: string;
  category: 'ambient' | 'upbeat' | 'jazz' | 'classical' | 'corporate' | 'workout' | 'chill';
  image: string;
  tracks: {
    name: string;
    artist: string;
    duration: number;
  }[];
  totalDuration: number;
  mood: 'relaxing' | 'energetic' | 'professional' | 'sophisticated' | 'motivating';
  availableFor: 'all' | string[]; // 'all' or array of client IDs
  createdBy: string; // sync2gear admin ID
  createdAt: Date;
  updatedAt: Date;
  active: boolean;
}

export const mockMusicTemplates: MusicTemplate[] = [
  {
    id: 'music-template1',
    title: 'Coffee Shop Vibes',
    description: 'Perfect acoustic and indie tracks for creating a cozy coffee shop atmosphere',
    category: 'chill',
    image: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=400&h=300&fit=crop',
    tracks: [
      { name: 'Morning Brew', artist: 'Acoustic Collective', duration: 195 },
      { name: 'Lazy Sunday', artist: 'Indie Cafe', duration: 210 },
      { name: 'Warm Latte', artist: 'Coffee House Jazz', duration: 180 },
    ],
    totalDuration: 585,
    mood: 'relaxing',
    availableFor: 'all',
    createdBy: 'user1',
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
    active: true,
  },
  {
    id: 'music-template2',
    title: 'Retail Energy',
    description: 'Upbeat pop and modern tracks to energize your retail space',
    category: 'upbeat',
    image: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=400&h=300&fit=crop',
    tracks: [
      { name: 'Shop Till You Drop', artist: 'Pop Collective', duration: 205 },
      { name: 'Feel Good Shopping', artist: 'Retail Beats', duration: 190 },
      { name: 'Happy Vibes', artist: 'Modern Pop', duration: 215 },
    ],
    totalDuration: 610,
    mood: 'energetic',
    availableFor: 'all',
    createdBy: 'user1',
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
    active: true,
  },
  {
    id: 'music-template3',
    title: 'Fine Dining Jazz',
    description: 'Sophisticated jazz selections for upscale dining experiences',
    category: 'jazz',
    image: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=400&h=300&fit=crop',
    tracks: [
      { name: 'Dinner at Eight', artist: 'Jazz Ensemble', duration: 240 },
      { name: 'Moonlight Serenade', artist: 'Smooth Jazz Trio', duration: 230 },
      { name: 'Evening Elegance', artist: 'Fine Dining Quartet', duration: 220 },
    ],
    totalDuration: 690,
    mood: 'sophisticated',
    availableFor: 'all',
    createdBy: 'user1',
    createdAt: new Date('2025-01-02'),
    updatedAt: new Date('2025-01-02'),
    active: true,
  },
  {
    id: 'music-template4',
    title: 'Office Focus',
    description: 'Ambient instrumental tracks to enhance productivity and concentration',
    category: 'ambient',
    image: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=400&h=300&fit=crop',
    tracks: [
      { name: 'Deep Work', artist: 'Productivity Sounds', duration: 300 },
      { name: 'Flow State', artist: 'Focus Music', duration: 280 },
      { name: 'Concentration', artist: 'Work Ambience', duration: 290 },
    ],
    totalDuration: 870,
    mood: 'professional',
    availableFor: 'all',
    createdBy: 'user1',
    createdAt: new Date('2025-01-03'),
    updatedAt: new Date('2025-01-03'),
    active: true,
  },
  {
    id: 'music-template5',
    title: 'Gym Motivation',
    description: 'High-energy workout tracks to keep your members pushing harder',
    category: 'workout',
    image: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=400&h=300&fit=crop',
    tracks: [
      { name: 'Beast Mode', artist: 'Workout Warriors', duration: 200 },
      { name: 'No Limits', artist: 'Fitness Beats', duration: 195 },
      { name: 'Power Hour', artist: 'Gym Anthems', duration: 210 },
    ],
    totalDuration: 605,
    mood: 'motivating',
    availableFor: 'all',
    createdBy: 'user1',
    createdAt: new Date('2025-01-04'),
    updatedAt: new Date('2025-01-04'),
    active: true,
  },
  {
    id: 'music-template6',
    title: 'Spa Serenity',
    description: 'Calming ambient sounds for wellness and spa environments',
    category: 'ambient',
    image: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=400&h=300&fit=crop',
    tracks: [
      { name: 'Tranquil Waters', artist: 'Spa Sounds', duration: 360 },
      { name: 'Peaceful Mind', artist: 'Wellness Music', duration: 340 },
      { name: 'Deep Relaxation', artist: 'Meditation Masters', duration: 380 },
    ],
    totalDuration: 1080,
    mood: 'relaxing',
    availableFor: 'all',
    createdBy: 'user1',
    createdAt: new Date('2025-01-05'),
    updatedAt: new Date('2025-01-05'),
    active: true,
  },
  {
    id: 'music-template7',
    title: 'Cocktail Lounge',
    description: 'Smooth lounge music perfect for bars and cocktail venues',
    category: 'jazz',
    image: 'https://images.unsplash.com/photo-1514933651103-005eec06c04b?w=400&h=300&fit=crop',
    tracks: [
      { name: 'Midnight Martini', artist: 'Lounge Collective', duration: 250 },
      { name: 'Smooth Operator', artist: 'Jazz Lounge', duration: 240 },
      { name: 'Late Night Groove', artist: 'Cocktail Jazz', duration: 260 },
    ],
    totalDuration: 750,
    mood: 'sophisticated',
    availableFor: 'all',
    createdBy: 'user1',
    createdAt: new Date('2025-01-06'),
    updatedAt: new Date('2025-01-06'),
    active: true,
  },
  {
    id: 'music-template8',
    title: 'Corporate Lobby',
    description: 'Professional background music for office lobbies and reception areas',
    category: 'corporate',
    image: 'https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=400&h=300&fit=crop',
    tracks: [
      { name: 'Professional Presence', artist: 'Corporate Sounds', duration: 270 },
      { name: 'Business Class', artist: 'Office Ambience', duration: 260 },
      { name: 'Executive Suite', artist: 'Corporate Music', duration: 280 },
    ],
    totalDuration: 810,
    mood: 'professional',
    availableFor: 'all',
    createdBy: 'user1',
    createdAt: new Date('2025-01-07'),
    updatedAt: new Date('2025-01-07'),
    active: true,
  },
  {
    id: 'music-template9',
    title: 'Brunch Classics',
    description: 'Light classical and contemporary tracks for brunch service',
    category: 'classical',
    image: 'https://images.unsplash.com/photo-1464454709131-ffd692591ee5?w=400&h=300&fit=crop',
    tracks: [
      { name: 'Sunday Morning', artist: 'Classical Brunch', duration: 300 },
      { name: 'Light Concerto', artist: 'Chamber Orchestra', duration: 290 },
      { name: 'Elegant Breakfast', artist: 'Morning Classics', duration: 310 },
    ],
    totalDuration: 900,
    mood: 'sophisticated',
    availableFor: 'all',
    createdBy: 'user1',
    createdAt: new Date('2025-01-08'),
    updatedAt: new Date('2025-01-08'),
    active: true,
  },
  {
    id: 'music-template10',
    title: 'Happy Hour Beats',
    description: 'Upbeat tracks to create an energetic happy hour atmosphere',
    category: 'upbeat',
    image: 'https://images.unsplash.com/photo-1470337458703-46ad1756a187?w=400&h=300&fit=crop',
    tracks: [
      { name: 'Friday Feeling', artist: 'Party Starters', duration: 220 },
      { name: 'Weekend Warm Up', artist: 'Happy Hour Band', duration: 210 },
      { name: 'Good Times', artist: 'Bar Beats', duration: 230 },
    ],
    totalDuration: 660,
    mood: 'energetic',
    availableFor: 'all',
    createdBy: 'user1',
    createdAt: new Date('2025-01-09'),
    updatedAt: new Date('2025-01-09'),
    active: true,
  },
];

export const mockSchedules: Schedule[] = [
  {
    id: 'schedule1',
    name: 'Hourly Promotions',
    clientId: 'client1',
    deviceIds: ['device1', 'device2'],
    enabled: true,
    schedule: {
      type: 'interval',
      intervalMinutes: 60,
      announcementIds: ['audio1'],
      avoidRepeat: true,
      quietHoursStart: '22:00',
      quietHoursEnd: '08:00',
    },
    createdAt: new Date('2025-01-08'),
    createdBy: 'user2',
    updatedAt: new Date('2025-01-08'),
  },
  {
    id: 'schedule2',
    name: 'Evening Timeline',
    clientId: 'client1',
    deviceIds: ['device1'],
    enabled: true,
    schedule: {
      type: 'timeline',
      cycleDurationMinutes: 30,
      announcements: [
        { announcementId: 'audio1', timestampSeconds: 300 }, // 5 mins
        { announcementId: 'audio2', timestampSeconds: 1500 }, // 25 mins
      ],
    },
    createdAt: new Date('2025-01-10'),
    createdBy: 'user2',
    updatedAt: new Date('2025-01-10'),
  },
];

export const mockPlayEvents: PlayEvent[] = [
  {
    id: 'event1',
    announcementId: 'audio1',
    deviceId: 'device1',
    clientId: 'client1',
    type: 'instant',
    status: 'completed',
    createdAt: new Date(Date.now() - 120000),
    createdBy: 'user2',
    deliveredAt: new Date(Date.now() - 119000),
    completedAt: new Date(Date.now() - 107000),
  },
  {
    id: 'event2',
    announcementId: 'audio2',
    deviceId: 'device3',
    clientId: 'client1',
    type: 'instant',
    status: 'pending',
    createdAt: new Date(Date.now() - 60000),
    createdBy: 'user2',
  },
];

export const mockAuditLogs: AuditLog[] = [
  {
    id: 'log1',
    userId: 'user2',
    userName: 'Coffee Shop Manager',
    action: 'upload',
    resource: 'music',
    resourceId: 'music1',
    clientId: 'client1',
    details: 'Uploaded Autumn Leaves.mp3',
    timestamp: new Date('2025-01-06T10:30:00'),
  },
  {
    id: 'log2',
    userId: 'user2',
    userName: 'Coffee Shop Manager',
    action: 'create',
    resource: 'schedule',
    resourceId: 'schedule1',
    clientId: 'client1',
    details: 'Created schedule: Hourly Promotions',
    timestamp: new Date('2025-01-08T14:20:00'),
  },
  {
    id: 'log3',
    userId: 'user1',
    userName: 'Admin User',
    action: 'create',
    resource: 'client',
    resourceId: 'client1',
    details: 'Created client: Downtown Coffee Shop',
    timestamp: new Date('2025-01-05T09:00:00'),
  },
];

// Channel Playlists - Mix of music and announcements
export const mockChannelPlaylists: ChannelPlaylist[] = [
  {
    id: 'channel1',
    name: 'Morning Rush - Ground Floor',
    description: 'Upbeat music with promotional announcements for morning customers',
    clientId: 'client1',
    floorIds: ['floor1'], // Ground Floor
    items: [
      { id: 'item1', type: 'music', contentId: 'music1', intervalMinutes: 15 },
      { id: 'item2', type: 'music', contentId: 'music2', intervalMinutes: 15 },
      { id: 'item3', type: 'announcement', contentId: 'audio1', intervalMinutes: 30 }, // Daily special every 30 min
      { id: 'item4', type: 'announcement', contentId: 'audio2', fixedTimes: ['19:30', '20:30'] }, // Closing soon at fixed times
    ],
    defaultMusicInterval: 15,
    defaultAnnouncementInterval: 30,
    shuffleMusic: true,
    shuffleAnnouncements: false,
    quietHoursStart: '22:00',
    quietHoursEnd: '07:00',
    enabled: true,
    createdAt: new Date('2025-01-12'),
    createdBy: 'user2',
    updatedAt: new Date('2025-01-15'),
  },
  {
    id: 'channel2',
    name: 'Relaxing Afternoon',
    description: 'Chill jazz music for afternoon ambiance',
    clientId: 'client1',
    floorIds: ['floor1', 'floor2'], // Both floors
    items: [
      { id: 'item5', type: 'music', contentId: 'music1' },
      { id: 'item6', type: 'music', contentId: 'music3' },
    ],
    defaultMusicInterval: 20,
    defaultAnnouncementInterval: 45,
    shuffleMusic: true,
    shuffleAnnouncements: true,
    enabled: true,
    createdAt: new Date('2025-01-13'),
    createdBy: 'user2',
    updatedAt: new Date('2025-01-13'),
  },
  {
    id: 'channel3',
    name: 'Promotional Power Hour',
    description: 'High-frequency announcements with background music',
    clientId: 'client1',
    floorIds: ['floor1'],
    items: [
      { id: 'item7', type: 'music', contentId: 'music2', intervalMinutes: 10 },
      { id: 'item8', type: 'announcement', contentId: 'audio1', intervalMinutes: 3 }, // Every 3 minutes
      { id: 'item9', type: 'announcement', contentId: 'audio1', fixedTimes: ['12:00', '15:00', '18:00'] }, // Lunch, afternoon, dinner
    ],
    defaultMusicInterval: 10,
    defaultAnnouncementInterval: 3,
    shuffleMusic: false,
    shuffleAnnouncements: false,
    quietHoursStart: '21:00',
    quietHoursEnd: '09:00',
    enabled: false, // Not currently active
    createdAt: new Date('2025-01-14'),
    createdBy: 'user2',
    updatedAt: new Date('2025-01-14'),
  },
];